#!/usr/bin/env node
// Toast Menus API V2 -> data.js menu region generator.
//
// Zero-dependency (Node 20+ global fetch, no package.json, no node_modules).
// Lives under .github/ so the repo's guardrails ESM grep ignores it and the
// no-build invariant is preserved. The served site stays 100% static.
//
// Flow:
//   1. auth  -> POST /authentication/v1/authentication/login  (client credentials)
//   2. check -> GET  /menus/v2/metadata   (cheap; lastUpdated timestamp)
//   3. pull  -> GET  /menus/v2/menus       (only if metadata changed)
//   4. splice the transformed menu into data.js between the TOAST-SYNC markers
//
// Exit codes: 0 = wrote a change OR clean no-op (up to date / creds absent);
//             1 = hard error (auth / API / parse failure).
//
// Local testing without live credentials:
//   TOAST_MENUS_FIXTURE=.github/scripts/fixtures/menus.sample.json node .github/scripts/toast-sync.mjs

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..', '..')
const DATA_JS = resolve(REPO_ROOT, 'data.js')
const STATE_FILE = resolve(HERE, '.toast-menu-state.json')

// --- Toast connection (from GitHub Actions secrets) ---
const HOST = process.env.TOAST_HOSTNAME || 'https://ws-api.toasttab.com'
const CLIENT_ID = process.env.TOAST_CLIENT_ID
const CLIENT_SECRET = process.env.TOAST_CLIENT_SECRET
const RESTAURANT_GUID = process.env.TOAST_RESTAURANT_GUID

// --- Conventions the restaurant controls (confirm with Kara/Gavin) ---
// Veg marker: a token Kara appends to a Toast item description to flag it
// vegetarian. It is stripped from the displayed description and sets veg:true.
const VEG_MARKER = process.env.TOAST_VEG_MARKER || '(v)'
// Toast menu-group names to EXCLUDE from the website (internal / online-only),
// comma-separated.
const EXCLUDE_GROUPS = (process.env.TOAST_EXCLUDE_GROUPS || '')
  .split(',').map(s => s.trim()).filter(Boolean)
// Optional per-group presentation overrides keyed by Toast group name, so the
// playful category titles + blurbs survive the pull. Example:
//   "Eggs": { title: "All Things Eggs", sub: "Comes with toast & spuds." }
const GROUP_OVERRIDES = {}

// ---------------------------------------------------------------------------

const slug = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const fmtPrice = (p) => (p == null || p === '') ? '' : Number(p).toFixed(2)
const q = (s) => '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'

// Recursively walk Toast menu groups; every group that has items becomes a
// category. Nested subgroups become their own categories.
function collect(group, categories, items) {
  if (!group || EXCLUDE_GROUPS.includes(group.name)) return
  const groupItems = group.menuItems || []
  if (groupItems.length) {
    const id = slug(group.name)
    const ov = GROUP_OVERRIDES[group.name] || {}
    categories.push({ id, title: ov.title || group.name, sub: ov.sub || null })
    for (const it of groupItems) {
      const raw = (it.description || '').trim()
      const veg = raw.includes(VEG_MARKER)
      const desc = veg ? raw.split(VEG_MARKER).join('').replace(/\s+/g, ' ').trim() : raw
      const entry = { cat: id, nm: it.name, desc, price: fmtPrice(it.price) }
      if (veg) entry.veg = true
      if (it.image) entry.img = it.image
      items.push(entry)
    }
  }
  for (const sub of (group.menuGroups || [])) collect(sub, categories, items)
}

// Toast /menus response -> { categories, items }.
function transform(payload) {
  const categories = []
  const items = []
  for (const menu of (payload.menus || [])) {
    for (const group of (menu.menuGroups || [])) collect(group, categories, items)
  }
  if (!categories.length) throw new Error('Toast returned no menu groups with items — refusing to blank the menu.')
  return { categories, items }
}

// Serialize the { categories, items } into the exact FT_DATA region text,
// including both markers. Matches the file's 2-space, unquoted-key style.
function renderRegion({ categories, items }) {
  const catLines = categories.map(
    (c) => `    { id: ${q(c.id)}, title: ${q(c.title)}, sub: ${c.sub == null ? 'null' : q(c.sub)} },`
  )
  const itemLines = items.map((it) => {
    let s = `    { cat: ${q(it.cat)}, nm: ${q(it.nm)}, desc: ${q(it.desc)}, price: ${q(it.price)}`
    if (it.veg) s += ', veg: true'
    if (it.img) s += `, img: ${q(it.img)}`
    return s + ' },'
  })
  return [
    '  // >>> TOAST-SYNC:START — generated by .github/scripts/toast-sync.mjs from Toast',
    '  // Menus API V2. Do not hand-edit this region; it is overwritten on each sync.',
    '  menuCategories: [',
    ...catLines,
    '  ],',
    '  menuItems: [',
    ...itemLines,
    '  ],',
    '  // <<< TOAST-SYNC:END',
  ].join('\n')
}

const REGION_RE = /[ \t]*\/\/ >>> TOAST-SYNC:START[\s\S]*?\/\/ <<< TOAST-SYNC:END/

async function spliceDataJs(region) {
  const src = await readFile(DATA_JS, 'utf8')
  if (!REGION_RE.test(src)) throw new Error('TOAST-SYNC markers not found in data.js')
  const next = src.replace(REGION_RE, region)
  if (next === src) return false
  await writeFile(DATA_JS, next)
  return true
}

async function login() {
  const r = await fetch(`${HOST}/authentication/v1/authentication/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ clientId: CLIENT_ID, clientSecret: CLIENT_SECRET, userAccessType: 'TOAST_MACHINE_CLIENT' }),
  })
  if (!r.ok) throw new Error(`Auth failed ${r.status}: ${await r.text()}`)
  const j = await r.json()
  const token = j?.token?.accessToken || j?.accessToken
  if (!token) throw new Error('No accessToken in auth response')
  return token
}

async function apiGet(token, path) {
  const r = await fetch(`${HOST}${path}`, {
    headers: { Authorization: `Bearer ${token}`, 'Toast-Restaurant-External-ID': RESTAURANT_GUID },
  })
  if (!r.ok) throw new Error(`GET ${path} failed ${r.status}: ${await r.text()}`)
  return r.json()
}

async function loadState() {
  try { return JSON.parse(await readFile(STATE_FILE, 'utf8')) } catch { return {} }
}
async function saveState(state) {
  await writeFile(STATE_FILE, JSON.stringify(state, null, 2) + '\n')
}

async function main() {
  // Offline path: transform a saved sample payload, no network.
  if (process.env.TOAST_MENUS_FIXTURE) {
    const payload = JSON.parse(await readFile(resolve(REPO_ROOT, process.env.TOAST_MENUS_FIXTURE), 'utf8'))
    const built = transform(payload)
    const changed = await spliceDataJs(renderRegion(built))
    console.log(`[fixture] ${changed ? 'wrote' : 'no change to'} data.js (${built.items.length} items).`)
    return
  }

  if (!CLIENT_ID || !CLIENT_SECRET || !RESTAURANT_GUID) {
    console.log('Toast credentials not configured — skipping (no-op). Set TOAST_CLIENT_ID, TOAST_CLIENT_SECRET, TOAST_RESTAURANT_GUID.')
    return
  }

  const token = await login()
  const meta = await apiGet(token, '/menus/v2/metadata')
  const lastUpdated = meta?.lastUpdated || meta?.lastPublished || null
  const state = await loadState()
  if (lastUpdated && state.lastUpdated === lastUpdated) {
    console.log(`Menu unchanged (lastUpdated=${lastUpdated}) — skipping pull.`)
    return
  }

  const menus = await apiGet(token, '/menus/v2/menus')
  const built = transform(menus)
  const changed = await spliceDataJs(renderRegion(built))
  await saveState({ lastUpdated, syncedItems: built.items.length })
  console.log(changed ? `Wrote data.js (${built.items.length} items).` : `data.js already current (${built.items.length} items).`)
}

main().catch((e) => { console.error(String(e?.stack || e)); process.exit(1) })
