// Menu + retail + press + buzz data for The Fly Trap
window.FT_DATA = {
  menuCategories: [
    { id: "eggs", title: "All Things Eggs", sub: "Comes with toast & smashed garlic fried potatoes when logical." },
    { id: "sweet", title: "Oh, Sugar Shack!", sub: null },
    { id: "salads", title: "Green Things", sub: "All salads come with grilled bread." },
    { id: "between", title: "Between Bread", sub: "Sandwiches come with fries, small salad or house spuds & something pickled." },
    { id: "other", title: "Other Stuff", sub: null },
    { id: "sides", title: "B-Sides", sub: "Add-ons & smaller plates." },
    { id: "drinks", title: "Whistle Wetters", sub: null },
  ],
  menuItems: [
    // Eggs
    { cat: "eggs", nm: "Green Eggs and Ham", desc: "Poblano pesto and jack cheese rumbled with eggs, sidled by seared city ham.", price: "14.95" },
    { cat: "eggs", nm: "Veggie Rumble", desc: "Red pepper, carrots, mushrooms, peas, spinach and provolone. Choose eggs or tofu.", price: "13.95", veg: true },
    { cat: "eggs", nm: "The Boot", desc: "Mussolini's fave — a rumble of eggs with fresh mozzarella, basil, tomatoes, & green olives.", price: "13.95" },
    { cat: "eggs", nm: "The Forager", desc: "Wild'n'mild 'shrooms, caramelized onion, smoked gouda & greens rumbled with eggs.", price: "14.95" },
    { cat: "eggs", nm: "Huevos Rancheros", desc: "Two eggs any style, crispy flour tortilla, black beans, jack cheese, jalapeños, pico & sour cream.", price: "13.95" },
    { cat: "eggs", nm: "Cowboy Curtis", desc: "Seared flank steak straddlin' a wildwest sauce, two eggs fried easy to hard & yippee kayay…pick your toast.", price: "18.95" },
    { cat: "eggs", nm: "Eggs ala Boring", desc: "Simply two eggs ($7.95), or two eggs with meat ($9.95).", price: "7.95" },
    { cat: "eggs", nm: "Red Flannel Hash", desc: "Hot spiced beef brisket, potatoes, beets & greens with horseradish-mini scallions.", price: "14.95" },
    { cat: "eggs", nm: "Crab Cakes and Eggs", desc: "Two crab chubs alongside a pair of eggs any style with a green chili tartar.", price: "17.95" },
    { cat: "eggs", nm: "El Burrito Bonito", desc: "Chorizo, scrambled eggs, house spuds & cheddar swaddled in a flour tortilla, topped with pico & sour cream.", price: "15.95" },
    { cat: "eggs", nm: "B.L.A.T.+C.", desc: "An omelette replete with pepper bacon, spinach, avocado, tomato & cheddar.", price: "14.95" },
    { cat: "eggs", nm: "Bocca al Lupo", desc: "Hot Italian sausage, peppers, onion, spinach & provolone stuffed in an omelette.", price: "14.95" },
    { cat: "eggs", nm: "Slacker Especial", desc: "An omelette filled with black beans, cheddar, chips, topped with pico & sour cream.", price: "13.95" },
    // Sweet
    { cat: "sweet", nm: "Gingerbread Waffle", desc: "With sautéed apples, cherries & cinnamon syrup.", price: "11.95", veg: true },
    { cat: "sweet", nm: "Granola", desc: "House mixed nuts, seeds & honey rolled oats with coconut, banana & vanilla yogurt.", price: "9.95", veg: true },
    { cat: "sweet", nm: "Mini-Muffin", desc: "Daily flavor.", price: "0.99", veg: true },
    { cat: "sweet", nm: "Oatmeal", desc: "Plain ($6) or with dried cherries & vanilla ice cream ($7.95).", price: "6.00", veg: true },
    // Salads
    { cat: "salads", nm: "Rob's Chop Chop", desc: "A 'Wunder' not to be missed. Greens, mushrooms, ham, salami, provolone, ceci beans & olives chopped together with creamy herb. Sm $12.95 / Lg $15.95.", price: "12.95" },
    { cat: "salads", nm: "Ensalada de Basura", desc: "Black beans, tomatoes, avocado, cheddar, greens, crispy tortillas, sour cream & guajillo dressing.", price: "15.95" },
    { cat: "salads", nm: "The Echo", desc: "Greens, feta, beets, kalamata olives, red onion, grape tomato, cucumber & chick peas with tomato vinaigrette.", price: "15.95", veg: true },
    { cat: "salads", nm: "House", desc: "Mixed greens, shaved onion, grape tomatoes. Choice of dressing. Side: $3.95.", price: "7.95", veg: true },
    // Sandwiches
    { cat: "between", nm: "B.L.T. & A.", desc: "Pepper bacon, lettuce, tomato & avocado on sourdough with garlic aioli.", price: "14.95" },
    { cat: "between", nm: "Pea Patch Papoose", desc: "Mushrooms, carrots, peppers, spinach, tomatoes & provolone in a flour tortilla with house mustard and poblano herb pesto schmear.", price: "13.95", veg: true },
    { cat: "between", nm: "Charmoula Chicken", desc: "North African spiced chicken thighs, jack cheese, caramelized onion on grilled sourdough with lemony garlic aioli.", price: "14.95" },
    { cat: "between", nm: "The Cheapsteak", desc: "Flank steak on grilled sourdough with swiss, balsamic onions, spinach, tomato & grainy mustard.", price: "18.95" },
    { cat: "between", nm: "Jeremy's Mess", desc: "A toasty mix of salami, sausage, sweet & hot peppers, olives, caramelized onion, hot mustard & provolone on a house roll.", price: "14.95" },
    { cat: "between", nm: "The Paddy Wagon", desc: "Brined brisket sliced thin and served warm with cool cabbage, smoked gouda & caramelized onion on grilled rye with jalapeño mustard.", price: "14.95" },
    { cat: "between", nm: "The E-Z Chi-Z", desc: "A grilled three-cheese on sourdough with kimchi, lil' pink mayo, cheddar & jack, topped with American cheese and baked until bubbling.", price: "12.95" },
    { cat: "between", nm: "The Burger", desc: "A ½ lb. of seasoned ground beef, house roll, Buzz Sauce & all the standard fixin's.", price: "14.95" },
    { cat: "between", nm: "Tempting Tempeh", desc: "Same as the burger, but for our vegetarian friends.", price: "13.95", veg: true },
    { cat: "between", nm: "Red Chili Salmon Burger", desc: "Shaved cucumber, ginger lime aioli & all the standard fixin's.", price: "17.95" },
    // Other
    { cat: "other", nm: "Crab Cake App", desc: "Two crab chubs, red chili greens, green chili tartar.", price: "13.95" },
    { cat: "other", nm: "Fried Rice", desc: "Brown rice, roasted mushrooms, veggies, tofu, red chilies, tamari & sesame. + chicken $15.95 / shrimp $16.95.", price: "14.95", veg: true },
    { cat: "other", nm: "Fire-Breathing Dragon", desc: "Chilled wheat noodles tossed in sambal peanut sauce with snap peas, basil, scallions and pickled cabbage. Grilled chicken or tofu.", price: "15.95" },
    { cat: "other", nm: "Mac Loves Cheese", desc: "Cheddar, smoked gouda & blue with cavatappi pasta, caramelized onion & herbs.", price: "13.95", veg: true },
    { cat: "other", nm: "Lemongrass Faux Bowl", desc: "Lemongrass and Thai chili broth with wheat noodles, sesame, roasted mushrooms, veggies. Chicken/tofu/shrimp.", price: "15.95" },
    { cat: "other", nm: "Howie's Noodles", desc: "Shrimp, fettuccine, cajun cream, tomatoes, scallion and parmesan.", price: "16.95" },
    // Sides
    { cat: "sides", nm: "Daily Soup", desc: "Cup $5.00 · Bowl $6.00.", price: "5.00" },
    { cat: "sides", nm: "House Spuds", desc: "Smashed garlic fried potatoes.", price: "3.95", veg: true },
    { cat: "sides", nm: "Fries", desc: "", price: "3.95", veg: true },
    { cat: "sides", nm: "Side Salad", desc: "Mixed greens, choice of dressing.", price: "3.95", veg: true },
    { cat: "sides", nm: "Toast", desc: "Sourdough, multigrain or rye.", price: "2.95", veg: true },
    { cat: "sides", nm: "Pepper Bacon", desc: "", price: "6.00" },
    { cat: "sides", nm: "Hot Italian Sausage", desc: "", price: "6.00" },
    { cat: "sides", nm: "Detroit Breakfast Links", desc: "", price: "6.00" },
    { cat: "sides", nm: "Grilled City Ham", desc: "", price: "6.00" },
    { cat: "sides", nm: "Chicken Thigh", desc: "", price: "6.00" },
    { cat: "sides", nm: "Tempeh Patty", desc: "", price: "6.00", veg: true },
    { cat: "sides", nm: "Tofu", desc: "", price: "5.00", veg: true },
    { cat: "sides", nm: "Seared Shrimp", desc: "", price: "7.00" },
    { cat: "sides", nm: "Black Beans", desc: "", price: "5.00", veg: true },
    // Drinks
    { cat: "drinks", nm: "Sabbath Coffee Roasters 'Ritual' Blend", desc: "Bottomless cup.", price: "2.95", veg: true },
    { cat: "drinks", nm: "Harney & Sons Loose Leaf Tea", desc: "", price: "3.95", veg: true },
    { cat: "drinks", nm: "Fresh Squeezed O.J.", desc: "Sm $3.95 · Lg $4.95.", price: "3.95", veg: true },
    { cat: "drinks", nm: "Fresh Squeezed Lemonades", desc: "", price: "3.95", veg: true },
    { cat: "drinks", nm: "Hot Cocoa", desc: "With whipped cream.", price: "2.95", veg: true },
    { cat: "drinks", nm: "Bottled Root Beer", desc: "", price: "2.95", veg: true },
    { cat: "drinks", nm: "Rootbeer Float", desc: "", price: "5.95", veg: true },
    { cat: "drinks", nm: "Fountain Drinks", desc: "", price: "2.50", veg: true },
    { cat: "drinks", nm: "Ito En Iced Green Tea", desc: "", price: "3.50", veg: true },
    { cat: "drinks", nm: "Fresh-Brewed Iced Tea", desc: "", price: "2.50", veg: true },
    { cat: "drinks", nm: "Arnie Palmer", desc: "Half iced tea, half lemonade.", price: "2.50", veg: true },
    { cat: "drinks", nm: "Lil' Can o' V-8", desc: "", price: "2.50", veg: true },
    { cat: "drinks", nm: "Grapefruit Juice", desc: "Sm $1.95 · Lg $2.95.", price: "1.95", veg: true },
  ],
  press: [
    { year: "2018", outlet: "Food Network Magazine", title: "50 States, 50 Breakfasts — Michigan picks the Fly Trap." },
    { year: "2016", outlet: "The Detroit News", title: "Profile of the room, the cooks, and why the eggs are like that." },
    { year: "2014", outlet: "Metro Times", title: "A long love letter to the marble bar and the seventeen flies." },
    { year: "2012", outlet: "Detroit Free Press", title: "21 Great Breakfasts — we made the cut." },
    { year: "2011", outlet: "Diners, Drive-Ins and Dives", title: "Guy Fieri orders the Cowboy Curtis. He says it's nuts." },
    { year: "2009", outlet: "NBC Nightly News", title: "A short segment on the Ferndale revival, filmed at Table 4." },
  ],
  paintings: [
    { src: "assets/paintings/fly-cowboy.jpg", label: "Fly Cowboy" },
    { src: "assets/paintings/fly-band.jpg", label: "Fly Band" },
    { src: "assets/paintings/fly-fly-fishing.jpg", label: "Fly Fly-Fishing" },
    { src: "assets/paintings/flies-dinner-date.jpg", label: "Flies on a Dinner Date" },
    { src: "assets/paintings/flies-kissing.jpg", label: "Flies Kissing" },
    { src: "assets/paintings/fly-art-class.jpg", label: "Fly Art Class" },
    { src: "assets/paintings/fly-eye-doctor.jpg", label: "Fly at the Eye Doctor" },
  ],
  // Daily buzz — rotating weekly schedule
  buzz: [
    { day: "Monday",    name: "The Bill Murray",  desc: "Slow-roasted brisket hash with cream-cheese chive scramble, crackly potatoes, jalapeño jam.", veg: false, price: "16.95" },
    { day: "Tuesday",   name: "Dolly Parton",     desc: "Gingerbread waffle with peach compote, whipped cream, candied pecans, & a 9-to-5 strong cup of coffee on the side.", veg: true, price: "13.95" },
    { day: "Wednesday", name: "RBG's Burrito",    desc: "Black bean & cotija burrito with poblano pesto, two eggs over easy, smoked-tomato salsa. Dissents are encouraged.", veg: true, price: "14.95" },
    { day: "Thursday",  name: "The Iggy Pop",     desc: "Detroit breakfast links, raw-power scramble, kimchi, and hashbrowns torched on the flat-top.", veg: false, price: "15.95" },
    { day: "Friday",    name: "Aretha's Crab Toast", desc: "Lump crab over grilled sourdough, dill aioli, tomato confit, soft-poached egg. Respect.", veg: false, price: "17.95" },
    { day: "Saturday",  name: "The Lizzo",        desc: "Two thick slices of cinnamon french toast, blueberry mascarpone, lemon curd, candied bacon. About damn time.", veg: false, price: "15.95" },
    { day: "Sunday",    name: "Stevie Wonder",    desc: "Eggs in a basket of buttery sourdough, signed-sealed-delivered hollandaise, country ham, garlic spuds.", veg: false, price: "16.95" },
  ],
  soup: { name: "Cream of Roasted Tomato & Fennel", desc: "Slow-roasted Roma tomatoes, fennel bulb, basil oil swirl, parmesan crisp on the side. Cup $5 / Bowl $6." },
  pastry: { name: "Brown-Butter Sour Cherry Galette", desc: "From the Sugar Shack — flaky butter dough, Michigan sour cherries, almond frangipane, demerara crust. While they last. $5.95." },
};
